// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mofvubybnqolupijdhdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vZnZ1YnlibnFvbHVwaWpkaGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTg0MjcsImV4cCI6MjA3NDU3NDQyN30.5HScp1T5kGxmEQQ-yFDjt2tr1iPlMnR5c2f2ex7kLdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});